name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # أو أي إصدار تريده
          distribution: 'temurin'  # أو 'adopt' أو 'zulu' حسب اختيارك

      - name: Compile Java files
        run: javac src/Calculator/*.java

      - name: Run Java program
        run: java -cp src Calculator.Prog
